[package]
name = "data_receiver"
version = "0.1.0"
authors = ["Tucker Strausbaugh <tckrsstrsbgh@gmail.com>"]

[[bin]]
name = "data_receiver"
path = "src/data_receiver.rs"

[dependencies]
serde_json = "*"
chrono = "*"
chrono-tz = "*"